name: Dev deployment (DABs)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

concurrency: 1

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Bundle validate
        run: databricks bundle validate
        working-directory: ./nyctaxi
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}

      - name: Bundle deploy (dev)
        run: databricks bundle deploy -t dev
        working-directory: ./nyctaxi
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}

      - name: Run job (smoke)
        run: databricks bundle run -t dev nyctaxi_job
        working-directory: ./nyctaxi
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
